lint.select = [
    'F',      # pyflakes
    'E',      # pycodestyle
    "A",      # prevent using keywords that clobber python builtins
    'I',      # isort
    'D',      # pydocstyle
    'UP',     # pyupgrade
    'RUF',    # the ruff developer's own rules
]
lint.ignore = [
    "D100",  # Missing docstring in public module
    "D103",  # Missing docstring in public function
    "D104",  # Missing docstring in public packageRuffD104
    "D203",  # incorrect-blank-line-before-class
    "D211",  # no-blank-line-before-class
    "D212",  # multi-line-summary-first-line
    "D213",  # multi-line-summary-second-line
]
line-length = 100
