name: Build and publish Docker image

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Log in to GitHub Container Registry
        if: github.event.pull_request.base.ref == 'master'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          # push: ${{ github.event.pull_request.base.ref == 'master' }}
          tags: |
            ghcr.io/${{ github.repository }}:v${{ github.run_number }}
            ghcr.io/${{ github.repository }}:latest
