name: Run Pre-Commit Hooks

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.13"

      - name: Install dependencies using uv
        run: |
          curl -sSL https://github.com/python-poetry/poetry/releases/download/1.6.1/poetry-1.6.1-linux-x86_64.tar.gz | tar -xz
          sudo mv poetry-1.6.1-linux-x86_64/poetry /usr/local/bin/
          uv install  # Use uv to install dependencies

      - name: Run Pre-Commit Hooks
        run: |
          pre-commit run --all-files
